"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeployRlog__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var DeployRlog__factory_1 = require("./DeployRlog__factory");
Object.defineProperty(exports, "DeployRlog__factory", { enumerable: true, get: function () { return DeployRlog__factory_1.DeployRlog__factory; } });
