"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Wallet__factory = exports.Tag__factory = exports.Page__factory = exports.Ownable__factory = exports.Log__factory = exports.Comment__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Comment__factory_1 = require("./Comment__factory");
Object.defineProperty(exports, "Comment__factory", { enumerable: true, get: function () { return Comment__factory_1.Comment__factory; } });
var Log__factory_1 = require("./Log__factory");
Object.defineProperty(exports, "Log__factory", { enumerable: true, get: function () { return Log__factory_1.Log__factory; } });
var Ownable__factory_1 = require("./Ownable__factory");
Object.defineProperty(exports, "Ownable__factory", { enumerable: true, get: function () { return Ownable__factory_1.Ownable__factory; } });
var Page__factory_1 = require("./Page__factory");
Object.defineProperty(exports, "Page__factory", { enumerable: true, get: function () { return Page__factory_1.Page__factory; } });
var Tag__factory_1 = require("./Tag__factory");
Object.defineProperty(exports, "Tag__factory", { enumerable: true, get: function () { return Tag__factory_1.Tag__factory; } });
var Wallet__factory_1 = require("./Wallet__factory");
Object.defineProperty(exports, "Wallet__factory", { enumerable: true, get: function () { return Wallet__factory_1.Wallet__factory; } });
