/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Relational, RelationalInterface } from "../Relational";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "address",
            name: "addr",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct Relational.Relationship",
        name: "relationship",
        type: "tuple",
      },
    ],
    name: "RelationshipAdded",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "targetId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "address",
            name: "addr",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
        ],
        internalType: "struct Relational.Relationship",
        name: "",
        type: "tuple",
      },
    ],
    name: "addBiDirectionalRelationship",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "targetId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "address",
            name: "addr",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
        ],
        internalType: "struct Relational.Relationship",
        name: "",
        type: "tuple",
      },
    ],
    name: "addUniDirectionalRelationship",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Relational__factory {
  static readonly abi = _abi;
  static createInterface(): RelationalInterface {
    return new utils.Interface(_abi) as RelationalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Relational {
    return new Contract(address, _abi, signerOrProvider) as Relational;
  }
}
