/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace Relational {
  export type RelationshipStruct = {
    addr: PromiseOrValue<string>;
    id: PromiseOrValue<BigNumberish>;
  };

  export type RelationshipStructOutput = [string, BigNumber] & {
    addr: string;
    id: BigNumber;
  };
}

export declare namespace Collection {
  export type CollectionContentsStruct = {
    id: PromiseOrValue<BigNumberish>;
    author: PromiseOrValue<string>;
    createdTimestamp: PromiseOrValue<BigNumberish>;
    name: PromiseOrValue<string>;
    relationships: Relational.RelationshipStruct[];
  };

  export type CollectionContentsStructOutput = [
    BigNumber,
    string,
    BigNumber,
    string,
    Relational.RelationshipStructOutput[]
  ] & {
    id: BigNumber;
    author: string;
    createdTimestamp: BigNumber;
    name: string;
    relationships: Relational.RelationshipStructOutput[];
  };
}

export interface CollectionInterface extends utils.Interface {
  functions: {
    "addBiDirectionalRelationship(uint256,(address,uint256))": FunctionFragment;
    "addUniDirectionalRelationship(uint256,(address,uint256))": FunctionFragment;
    "collectionCount()": FunctionFragment;
    "collections(uint256)": FunctionFragment;
    "create(string,(address,uint256)[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addBiDirectionalRelationship"
      | "addUniDirectionalRelationship"
      | "collectionCount"
      | "collections"
      | "create"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addBiDirectionalRelationship",
    values: [PromiseOrValue<BigNumberish>, Relational.RelationshipStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addUniDirectionalRelationship",
    values: [PromiseOrValue<BigNumberish>, Relational.RelationshipStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collections",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [PromiseOrValue<string>, Relational.RelationshipStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addBiDirectionalRelationship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addUniDirectionalRelationship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;

  events: {
    "CollectionCreated(uint256,tuple)": EventFragment;
    "RelationshipAdded(uint256,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CollectionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelationshipAdded"): EventFragment;
}

export interface CollectionCreatedEventObject {
  id: BigNumber;
  collection: Collection.CollectionContentsStructOutput;
}
export type CollectionCreatedEvent = TypedEvent<
  [BigNumber, Collection.CollectionContentsStructOutput],
  CollectionCreatedEventObject
>;

export type CollectionCreatedEventFilter =
  TypedEventFilter<CollectionCreatedEvent>;

export interface RelationshipAddedEventObject {
  id: BigNumber;
  relationship: Relational.RelationshipStructOutput;
}
export type RelationshipAddedEvent = TypedEvent<
  [BigNumber, Relational.RelationshipStructOutput],
  RelationshipAddedEventObject
>;

export type RelationshipAddedEventFilter =
  TypedEventFilter<RelationshipAddedEvent>;

export interface Collection extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CollectionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addBiDirectionalRelationship(
      collectionID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addUniDirectionalRelationship(
      collectionID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectionCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    collections(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string] & {
        id: BigNumber;
        author: string;
        createdTimestamp: BigNumber;
        name: string;
      }
    >;

    create(
      name: PromiseOrValue<string>,
      relationships: Relational.RelationshipStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addBiDirectionalRelationship(
    collectionID: PromiseOrValue<BigNumberish>,
    relationship: Relational.RelationshipStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addUniDirectionalRelationship(
    collectionID: PromiseOrValue<BigNumberish>,
    relationship: Relational.RelationshipStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectionCount(overrides?: CallOverrides): Promise<BigNumber>;

  collections(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, string] & {
      id: BigNumber;
      author: string;
      createdTimestamp: BigNumber;
      name: string;
    }
  >;

  create(
    name: PromiseOrValue<string>,
    relationships: Relational.RelationshipStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addBiDirectionalRelationship(
      collectionID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    addUniDirectionalRelationship(
      collectionID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    collectionCount(overrides?: CallOverrides): Promise<BigNumber>;

    collections(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string] & {
        id: BigNumber;
        author: string;
        createdTimestamp: BigNumber;
        name: string;
      }
    >;

    create(
      name: PromiseOrValue<string>,
      relationships: Relational.RelationshipStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CollectionCreated(uint256,tuple)"(
      id?: null,
      collection?: null
    ): CollectionCreatedEventFilter;
    CollectionCreated(
      id?: null,
      collection?: null
    ): CollectionCreatedEventFilter;

    "RelationshipAdded(uint256,tuple)"(
      id?: null,
      relationship?: null
    ): RelationshipAddedEventFilter;
    RelationshipAdded(
      id?: null,
      relationship?: null
    ): RelationshipAddedEventFilter;
  };

  estimateGas: {
    addBiDirectionalRelationship(
      collectionID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addUniDirectionalRelationship(
      collectionID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectionCount(overrides?: CallOverrides): Promise<BigNumber>;

    collections(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    create(
      name: PromiseOrValue<string>,
      relationships: Relational.RelationshipStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addBiDirectionalRelationship(
      collectionID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addUniDirectionalRelationship(
      collectionID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectionCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collections(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    create(
      name: PromiseOrValue<string>,
      relationships: Relational.RelationshipStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
