/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace Relational {
  export type RelationshipStruct = {
    addr: PromiseOrValue<string>;
    id: PromiseOrValue<BigNumberish>;
  };

  export type RelationshipStructOutput = [string, BigNumber] & {
    addr: string;
    id: BigNumber;
  };
}

export declare namespace Tag {
  export type TagContentsStruct = {
    id: PromiseOrValue<BigNumberish>;
    author: PromiseOrValue<string>;
    createdTimestamp: PromiseOrValue<BigNumberish>;
    name: PromiseOrValue<string>;
    relationships: Relational.RelationshipStruct[];
  };

  export type TagContentsStructOutput = [
    BigNumber,
    string,
    BigNumber,
    string,
    Relational.RelationshipStructOutput[]
  ] & {
    id: BigNumber;
    author: string;
    createdTimestamp: BigNumber;
    name: string;
    relationships: Relational.RelationshipStructOutput[];
  };
}

export interface TagInterface extends utils.Interface {
  functions: {
    "addBiDirectionalRelationship(uint256,(address,uint256))": FunctionFragment;
    "addUniDirectionalRelationship(uint256,(address,uint256))": FunctionFragment;
    "create(string,(address,uint256)[])": FunctionFragment;
    "tagCount()": FunctionFragment;
    "tags(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addBiDirectionalRelationship"
      | "addUniDirectionalRelationship"
      | "create"
      | "tagCount"
      | "tags"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addBiDirectionalRelationship",
    values: [PromiseOrValue<BigNumberish>, Relational.RelationshipStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addUniDirectionalRelationship",
    values: [PromiseOrValue<BigNumberish>, Relational.RelationshipStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [PromiseOrValue<string>, Relational.RelationshipStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "tagCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tags",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addBiDirectionalRelationship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addUniDirectionalRelationship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tagCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tags", data: BytesLike): Result;

  events: {
    "RelationshipAdded(uint256,tuple)": EventFragment;
    "TagCreated(uint256,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RelationshipAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TagCreated"): EventFragment;
}

export interface RelationshipAddedEventObject {
  id: BigNumber;
  relationship: Relational.RelationshipStructOutput;
}
export type RelationshipAddedEvent = TypedEvent<
  [BigNumber, Relational.RelationshipStructOutput],
  RelationshipAddedEventObject
>;

export type RelationshipAddedEventFilter =
  TypedEventFilter<RelationshipAddedEvent>;

export interface TagCreatedEventObject {
  id: BigNumber;
  tag: Tag.TagContentsStructOutput;
}
export type TagCreatedEvent = TypedEvent<
  [BigNumber, Tag.TagContentsStructOutput],
  TagCreatedEventObject
>;

export type TagCreatedEventFilter = TypedEventFilter<TagCreatedEvent>;

export interface Tag extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TagInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addBiDirectionalRelationship(
      tagID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addUniDirectionalRelationship(
      tagID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    create(
      name: PromiseOrValue<string>,
      relationships: Relational.RelationshipStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tagCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    tags(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string] & {
        id: BigNumber;
        author: string;
        createdTimestamp: BigNumber;
        name: string;
      }
    >;
  };

  addBiDirectionalRelationship(
    tagID: PromiseOrValue<BigNumberish>,
    relationship: Relational.RelationshipStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addUniDirectionalRelationship(
    tagID: PromiseOrValue<BigNumberish>,
    relationship: Relational.RelationshipStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  create(
    name: PromiseOrValue<string>,
    relationships: Relational.RelationshipStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tagCount(overrides?: CallOverrides): Promise<BigNumber>;

  tags(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, string] & {
      id: BigNumber;
      author: string;
      createdTimestamp: BigNumber;
      name: string;
    }
  >;

  callStatic: {
    addBiDirectionalRelationship(
      tagID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    addUniDirectionalRelationship(
      tagID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    create(
      name: PromiseOrValue<string>,
      relationships: Relational.RelationshipStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    tagCount(overrides?: CallOverrides): Promise<BigNumber>;

    tags(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string] & {
        id: BigNumber;
        author: string;
        createdTimestamp: BigNumber;
        name: string;
      }
    >;
  };

  filters: {
    "RelationshipAdded(uint256,tuple)"(
      id?: null,
      relationship?: null
    ): RelationshipAddedEventFilter;
    RelationshipAdded(
      id?: null,
      relationship?: null
    ): RelationshipAddedEventFilter;

    "TagCreated(uint256,tuple)"(id?: null, tag?: null): TagCreatedEventFilter;
    TagCreated(id?: null, tag?: null): TagCreatedEventFilter;
  };

  estimateGas: {
    addBiDirectionalRelationship(
      tagID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addUniDirectionalRelationship(
      tagID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    create(
      name: PromiseOrValue<string>,
      relationships: Relational.RelationshipStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tagCount(overrides?: CallOverrides): Promise<BigNumber>;

    tags(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addBiDirectionalRelationship(
      tagID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addUniDirectionalRelationship(
      tagID: PromiseOrValue<BigNumberish>,
      relationship: Relational.RelationshipStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    create(
      name: PromiseOrValue<string>,
      relationships: Relational.RelationshipStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tagCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tags(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
